"""session token column

Revision ID: 0fe7b6e9e92a
Revises: 85ffbb672f83
Create Date: 2020-06-20 18:14:59.442632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fe7b6e9e92a'
down_revision = '85ffbb672f83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('session_token', sa.String(length=43), nullable=True))
    op.create_index(op.f('ix_users_session_token'), 'users', ['session_token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_session_token'), table_name='users')
    op.drop_column('users', 'session_token')
    # ### end Alembic commands ###
